max-item-count: -1
#sleep: 1000
chunk-size: 1
generator:
  map: "#c.hgetall('node:'.concat(#c.srandmember('nodes')))"
  fields:
    SKU: "nextId(20000,'%09d')"
redisearch:
  search:
    index: stock
    query: '@DC_ID:{DC_ID}'