partitions: 2
generator:
  max: 1000000
  map: "#c.hgetall('node:'.concat(#c.smembers('nodes').get(current(10000)%3568)))"
  fields:
    SKU: "nextId(10000,'%09d')"
redis:
  search:
    add:
      index: stock
      keys: DC_ID,SKU
      drop: true
      schema:
      - name: DC_ID
        sortable: true
      - name: SKU
        sortable: true
      - name: GID_MKT_CD
        sortable: true
      - name: DC_TYP_CD
        sortable: true
      - name: DC_DESC
      - name: CITY_NM
        sortable: true
      - name: ST_PROV_CD
        sortable: true
      - name: CTRY_CD
        sortable: true
      - name: BRD_CD
        sortable: true
      - name: LOCATION
        type: geo
      - name: GIFTWRAP
        sortable: true
      - name: NEXTDAY
        sortable: true
      - name: POBOX
        sortable: true            
      - name: ONHAND
        type: numeric 
        sortable: true
      - name: HOLD
        type: numeric
        sortable: true
      - name: RESERVED
        type: numeric
        sortable: true
      - name: ALLOCATED
        type: numeric
        sortable: true
      - name: BACKORDERED
        type: numeric
        sortable: true
      - name: EXCLUDED
        type: numeric
        sortable: true